// flow-typed signature: 1174a6140f5d17050216deb8f619548f
// flow-typed version: <<STUB>>/@types/dotenv_v^2.0.18/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/dotenv' {
  declare module.exports: any;
}
