// flow-typed signature: 8f3221dd9e09f065329c184a536fb5df
// flow-typed version: <<STUB>>/@types/express_v^4.0.33/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
