// flow-typed signature: 4d70697127c7c31a598e9a5826c549a4
// flow-typed version: <<STUB>>/@types/mixpanel_v^0.0.28/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mixpanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mixpanel' {
  declare module.exports: any;
}
