// flow-typed signature: 54cdead5cddf14396d7c9f6f4fa09936
// flow-typed version: <<STUB>>/@types/mixpanel_v^0.0.28/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mixpanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mixpanel' {
  declare module.exports: any;
}
