// flow-typed signature: 75e3ab71d6646a3f56f2401da81b9fb3
// flow-typed version: <<STUB>>/@types/request-promise_v^3.0.32/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request-promise' {
  declare module.exports: any;
}
