// flow-typed signature: c50c01ce2db92eb84ea5dcac0f3da989
// flow-typed version: <<STUB>>/@types/winston_v^0.0.28/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/winston' {
  declare module.exports: any;
}
