// flow-typed signature: 9b0c0c1be2fddfc52eb7195be371d3e4
// flow-typed version: <<STUB>>/@types/winston_v^0.0.28/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/winston' {
  declare module.exports: any;
}
