// flow-typed signature: 65baedf1887e298d8de771f5ca9d17ea
// flow-typed version: <<STUB>>/localtunnel_v^1.8.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localtunnel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'localtunnel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'localtunnel/client' {
  declare module.exports: any;
}

declare module 'localtunnel/lib/HeaderHostTransformer' {
  declare module.exports: any;
}

declare module 'localtunnel/lib/Tunnel' {
  declare module.exports: any;
}

declare module 'localtunnel/lib/TunnelCluster' {
  declare module.exports: any;
}

declare module 'localtunnel/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'localtunnel/client.js' {
  declare module.exports: $Exports<'localtunnel/client'>;
}
declare module 'localtunnel/lib/HeaderHostTransformer.js' {
  declare module.exports: $Exports<'localtunnel/lib/HeaderHostTransformer'>;
}
declare module 'localtunnel/lib/Tunnel.js' {
  declare module.exports: $Exports<'localtunnel/lib/Tunnel'>;
}
declare module 'localtunnel/lib/TunnelCluster.js' {
  declare module.exports: $Exports<'localtunnel/lib/TunnelCluster'>;
}
declare module 'localtunnel/test/index.js' {
  declare module.exports: $Exports<'localtunnel/test/index'>;
}
