// flow-typed signature: 4d400b67d76952b3c3e68bd9069f6ba8
// flow-typed version: <<STUB>>/mixpanel_v^0.5.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mixpanel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mixpanel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mixpanel/example' {
  declare module.exports: any;
}

declare module 'mixpanel/lib/mixpanel-node' {
  declare module.exports: any;
}

declare module 'mixpanel/test/alias' {
  declare module.exports: any;
}

declare module 'mixpanel/test/config' {
  declare module.exports: any;
}

declare module 'mixpanel/test/import' {
  declare module.exports: any;
}

declare module 'mixpanel/test/people' {
  declare module.exports: any;
}

declare module 'mixpanel/test/send_request' {
  declare module.exports: any;
}

declare module 'mixpanel/test/track' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mixpanel/example.js' {
  declare module.exports: $Exports<'mixpanel/example'>;
}
declare module 'mixpanel/lib/mixpanel-node.js' {
  declare module.exports: $Exports<'mixpanel/lib/mixpanel-node'>;
}
declare module 'mixpanel/test/alias.js' {
  declare module.exports: $Exports<'mixpanel/test/alias'>;
}
declare module 'mixpanel/test/config.js' {
  declare module.exports: $Exports<'mixpanel/test/config'>;
}
declare module 'mixpanel/test/import.js' {
  declare module.exports: $Exports<'mixpanel/test/import'>;
}
declare module 'mixpanel/test/people.js' {
  declare module.exports: $Exports<'mixpanel/test/people'>;
}
declare module 'mixpanel/test/send_request.js' {
  declare module.exports: $Exports<'mixpanel/test/send_request'>;
}
declare module 'mixpanel/test/track.js' {
  declare module.exports: $Exports<'mixpanel/test/track'>;
}
