// flow-typed signature: d9fa414c6cefb9d4b902309467ce7035
// flow-typed version: <<STUB>>/to-markdown_v^3.0.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-markdown/dist/to-markdown' {
  declare module.exports: any;
}

declare module 'to-markdown/lib/gfm-converters' {
  declare module.exports: any;
}

declare module 'to-markdown/lib/html-parser' {
  declare module.exports: any;
}

declare module 'to-markdown/lib/md-converters' {
  declare module.exports: any;
}

declare module 'to-markdown/test/gfm-test' {
  declare module.exports: any;
}

declare module 'to-markdown/test/to-markdown-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-markdown/dist/to-markdown.js' {
  declare module.exports: $Exports<'to-markdown/dist/to-markdown'>;
}
declare module 'to-markdown/index' {
  declare module.exports: $Exports<'to-markdown'>;
}
declare module 'to-markdown/index.js' {
  declare module.exports: $Exports<'to-markdown'>;
}
declare module 'to-markdown/lib/gfm-converters.js' {
  declare module.exports: $Exports<'to-markdown/lib/gfm-converters'>;
}
declare module 'to-markdown/lib/html-parser.js' {
  declare module.exports: $Exports<'to-markdown/lib/html-parser'>;
}
declare module 'to-markdown/lib/md-converters.js' {
  declare module.exports: $Exports<'to-markdown/lib/md-converters'>;
}
declare module 'to-markdown/test/gfm-test.js' {
  declare module.exports: $Exports<'to-markdown/test/gfm-test'>;
}
declare module 'to-markdown/test/to-markdown-test.js' {
  declare module.exports: $Exports<'to-markdown/test/to-markdown-test'>;
}
